baseURL = 'https://kitchenowl.org/'
languageCode = 'en-us'
title = 'KitchenOwl'

enableInlineShortcodes = true
disableKinds = ['taxonomy', 'term']

[params]
  author = 'Tom Bursch'
  description = "KitchenOwl is a smart grocery list and recipe manager. Easily add items to your shopping list before you go shopping or create recipes and get cooking suggestions."
  theme_color = "#20ac64"

[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[markup.goldmark.renderer]
unsafe = true

[menu]
main = [
    { name = 'docs', url = 'https://docs.kitchenowl.org/' }
]
